### PR TITLE
gem: thor v0.20.0

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR updates `thor` to the next minor version.

[Changelog](https://github.com/erikhuda/thor/blob/master/CHANGELOG.md#0200)

### CODE REVIEW

**Comment by olleolleolle** [comment]
@indirect r?

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Comment by bronzdoc** [comment]
@olleolleolle i think this just needs a rebase to land:)

**Comment by olleolleolle** [comment]
How about I just open a new PR.

**Pull request closed without merging**
