### PR TITLE
Rake task doc: drop fix_github_line_breaks filter; change to gfm Pandoc formatter

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR tries to run the Rake `doc` task without Pandoc errors or warnings, to repair documentation generation.

The `doc` Rake task calls a list of Pandoc Filters. This PR removes one of those Filters.

See #203

# Benefits

This change made the files at least _render_, and the content line-breaks is not created using double line-breaks.

The change has 3 commits. The last commit is the "regenerate the docs with this". It's included, so that any troublesome renderings are visible here.

# Changes

Some things have **changed** with us using `gfm` as a pandoc Markdown formatter.

- `> $ gemstash setup --redo` the `--` becomes a n-dash or something (the `smart` extension of Pandoc is doing this). _Work-around_: I added code formatting back-ticks around the shell example
- CHANGE in the output Markdown content: [ATX headers](https://pandoc.org/MANUAL.html#headers) are now the rendered default. (`#` instead of `-----`). [All about Pandoc Headers](https://pandoc.org/MANUAL.html#headers).

> `--atx-headers` 
> Use ATX-style headers in Markdown output. The default is to use setext-style headers for levels 1-2, and then ATX headers. (**Note**: for `gfm` output, ATX headers are always used.)

# Questions for reviewer

- Does this change any of the other filters? Their meaning, their input/output?
- Am I missing some important change in output?
- Does this work on your computer?

<details>

Versions used

```
$ pandoc --version
pandoc 2.4
Compiled with pandoc-types 1.17.5.4, texmath 0.11.1.2, skylighting 0.7.4
Default user data directory: /Users/olle/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

$ ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]
```

</details>

### CODE REVIEW

**Comment by indirect** [comment]
I don't think I can answer any of those questions, but I am in favor of docs that actually generate... on Travis would be best, so we can potentially auto-release when a Travis build passes for a new tag?

**Comment by bronzdoc** [comment]
> Does this change any of the other filters? Their meaning, their input/output?
I don't think so since the only filter you are changing is `markdown_github`, unless i'm missing something?

> Am I missing some important change in output?
I'm not 100% sure about that, since i'm not a pandoc expert, but markdown_github waa only used to for json output and i don't see any other output being used with `markdown_github` in the codebase.

Does this work on your computer?
It removes the warnings as you mention, so yes it works, but it does not solve the problem of https://github.com/bundler/gemstash/issues/203 (Error: Could not find command "readme")

I'll say lets merge this @olleolleolle  since is replacing a deprecated pandoc filter for what pandoc recomends we change it toif we encounter any other problems regarding pandoc we can create another PR and fix them along the way.

Just please squash your commits into meaningful chunks or remove the "WIP" of the commit message, thanks for this!

**Comment by bronzdoc** [comment]
@olleolleolle please use @bundletbot to merge PR's thanks!

**Comment by olleolleolle** [comment]
Ouch, _yes_!

**Pull request merged**
