### PR TITLE
Update rubocop version and update files to be inline with new cops

### PR DESCRIPTION
**Pull request by bronzdoc**
Update rubocop and remove deprecated cop
related to https://github.com/bundler/gemstash/pull/198

### CODE REVIEW

**Comment by bronzdoc** [comment]
@olleolleolle want to give it a look?

**Comment by bronzdoc** [comment]
2.4.1 failed 😱

**Comment by olleolleolle** [comment]
@bundler/bundlerbot +1

**Comment by bronzdoc** [comment]
@olleolleolle is just @bundlerbot r+

**Comment by bronzdoc** [comment]
@bundlerbot r+

**Pull request merged**
