### PR TITLE
Added Ruby 2.4 to the build matrix

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by olleolleolle** [comment]
You could also bump jruby to 9.1.7.0 now that that version's published as stable.

**Comment by olleolleolle** [comment]
@smellsblue This would be quite good, yeah?

**Comment by smellsblue** [comment]
@olleolleolle yes! Good idea! I'll update that in the 1.0 branch, as I'm prepping for a release now.

**Comment by smellsblue** [comment]
Postponing upgrading JRuby because we are hitting this in Travis: https://github.com/sickill/rainbow/issues/48 (example: https://travis-ci.org/bundler/gemstash/jobs/196031999)

**Comment by olleolleolle** [comment]
Is upgrading rubygems not a fix?

**Comment by olleolleolle** [comment]
I'm away from a good keyboard, but I'd ask you to add gem update --system for a fix of this. 2.6.9 should have it.

**Comment by smellsblue** [comment]
@olleolleolle I'm not sure, is that something that is easily supported within Travis...? (I haven't looked into it)

**Pull request merged**
