### PR TITLE
Typo fix in changelog tool

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR fixes a typo in text interactively presented to the user.

### CODE REVIEW

**Comment by olleolleolle** [comment]
@indirect r?

**Comment by jules2689** [comment]
No idea if I have access to this, but let's try 😆 

@bundlerbot r+

**Comment by jules2689** [comment]
@bundlerbot r+

**Comment by hmistry** [comment]
@bundlerbot retry

**Comment by jules2689** [comment]
@bundlerbot retry

**Pull request merged**
