### PR TITLE
Add a health check

### LINKED ISSUE #145: Add health check endpoint
When our team trying to deploy gemstash to our servers, we immediately found that there's no health check endpoint for load balancer to check.

Is there any existing endpoint for that purpose? Otherwise, is there any way to manually insert rack middleware?

I would like to help but I need your inputs. Thanks!

### PR DESCRIPTION
**Pull request by smellsblue**
This fixes #145 

The health endpoint is at `/health` and will check that reading and writing from storage is working.

If you want a health endpoint that doesn't do any work, you can use `/health/heartbeat`.

The HTTP status code will indicate success vs failure (200 vs 500), and you will receive a JSON response that will indicate the breakdown of what succeeded vs failed.

- [x] Add health check endpoint
- [x] Test health check endpoint
- [x] Include a check that the database connections work ok
- [x] Document health check endpoint

### CODE REVIEW

**Comment by olleolleolle** [comment]
@smellsblue Is there anything else you want us to have for this to be a healthcheck endpoint?

**Comment by smellsblue** [comment]
@olleolleolle I was hoping to get a review, but then got caught up in other work. If you are happy with what I've done, I can merge it now. I looked at the build failures, and I don't think they are related to my changes.

**Comment by olleolleolle** [comment]
@smellsblue I am quite happy with these changes!

The build failures do look unrelated.

LGTM!

:hearts: :yellow_heart: :green_heart: :blue_heart: :purple_heart:

**Comment by dlackty** [comment]
@smellsblue We've tried this on production and got this error randomly:
```Mysql2::Error: Duplicate entry 'health_check:fake_gem_name' for key 'rubygems_name_index'```

Guessed some additional check needs to be performed before inserting.

**Pull request merged**
