### PR TITLE
Avoid filesystem limits using a trie

### PR DESCRIPTION
**Pull request by smellsblue**
Implement storage trie based on idea from @pcarranza in discussion for #18.

All tests are passing with no additional changes... should I write a test that fails if the storage isn't using a trie though?

### CODE REVIEW

**Comment by pcarranza** [comment]
Let me get the weird cases we will find down the line to add tests for those and see what happens there.

**Comment by smellsblue** [comment]
I can already think of a case that will fail... `-` seems fine on my machine, but I bet `.` would do bad things.

However, a simple regex gsub I think would fix it... maybe gsub anything not in a set of acceptable characters? Like:
```
trie_parents = @name[0...3].gsub(/[^0-9a-zA-Z]/, "_").split("")
```

**Comment by smellsblue** [comment]
hmmm, now that I think of it, the `.` probably wouldn't really pose a problem... it would essentially get ignored in the File.join, but it wouldn't be added in a trie manner, so I think gsubbing everything outside a certain range might still be the best option

**Comment by pcarranza** [comment]
This is the whole data sample of what we can find with current specs:
```
["_", "-", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "."]
```

**Comment by pcarranza** [comment]
So, yeah, maybe replace the . with something else that is not so full of meaning at the filesystem level.

And downcase to prevent the OSX HFS stupidity

**Comment by pcarranza** [comment]
:+1:

**Pull request merged**
