### PR TITLE
Breaking change: remove unyank support

### LINKED ISSUE #120: Rubygems parity: Remove '--undo' option in 'gem yank'
In Nov 2015, this commit https://github.com/rubygems/rubygems/commit/952bbb7c1068f340dcd74b9a5b4c18cdce8aedb7 removed the `yank --undo` option:

> Remove '--undo' option in 'gem yank'
> Unyanking of gems is no longer supported.

This issue calls for gemstash to have that same behavior.

This test currently fails due to this, when using a Rubygems new enough for this to appear (Example: jruby-9.1.6.0 has a quite new one.):

```
Failures:
  1) gemstash integration tests interacting with private gems unyanking a gem adds valid gems back to the server
     Failure/Error: expect(execute("gem", ["yank", "--key", "test", gem_name, "--version", gem_version, "--undo"], env: env)).
     
       expected 'gem yank --key test speaker --version 0.1.0 --undo' in '/home/travis/build/bundler/gemstash' to exit with a success code, but it didn't.
       the command output was:
       ERROR:  While executing gem ... (OptionParser::InvalidOption)
           invalid option: --undo
     # ./spec/integration_spec.rb:143:in `block in (root)'
     # ./spec/spec_helper.rb:36:in `block in /home/travis/build/bundler/gemstash/spec/spec_helper.rb'
Finished in 1 minute 39.09 seconds (files took 4.61 seconds to load)
```

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR removes the `unyank` command from Gemstash. Fixes #120.

It also changes the build to use **Travis' default build step** of `bundle exec rake`.

### Background

- After Gemstash updated its JRuby, a test failed on JRuby 9.1.6.0, which ships with a more modern Rubygems. 
- That failing test was about _unyanking gems_ - a now-removed Rubygems feature (See #120.)

### Solution

- This PR removes the `unyank` feature from Gemstash
- The documentation was updated to reflect the lack of unyank
 
_Also_: Hello, and thank you for this project.

### CODE REVIEW

**Comment by indirect** [comment]
LGTM. 👍

@smellsblue, I set up @bundlerbot to watch this repo since we are using it on bundler/bundler and rubygems/rubygems. The bot is effectively a fully-automated way to say "I would like to create a merge commit from this PR, run the tests, and fast-forward to the merge commit if the tests pass". We've found it super, super useful on Bundler, but no pressure to use it if you don't want to. There are usage instructions at https://bundlerbot-homu.herokuapp.com.

**Comment by smellsblue** [comment]
@indirect awesome! thanks! I'll definitely start using it :smile:

**Comment by olleolleolle** [comment]
@jules2689 https://github.com/bundler/gemstash/blob/master/rake/changelog.rb Perhaps the CHANGELOG.md is created and updated by this script, from the awesome metadata in this issue?

**Comment by jules2689** [comment]
Oh interesting

**Comment by olleolleolle** [comment]
One of those "RSpec had a hard time leaving" flakes:

/home/travis/build/bundler/gemstash/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.6.0/exe/rspec: stream closed (IOError)

**Comment by indirect** [comment]
Wow, I want automated changelogs 😲

**Comment by indirect** [comment]
Restarted the build. 👍

**Comment by indirect** [comment]
@bundlerbot r+

**Pull request merged**
