### PR TITLE
Add start/stop command gemstash outputs

### PR DESCRIPTION
**Pull request by farukaydin**
Fixes https://github.com/bundler/gemstash/issues/56

I didn't add any test since I think it doesn't need.

### CODE REVIEW

**Comment by pcarranza** [comment]
Just wonder if it makes more sense to do it with `cli.say` rather than the logger. Then you can even say it in green :smile: 

@smellsblue thoughts?

**Comment by farukaydin** [comment]
@pcarranza updated like you mentioned. I think it's better (and green :smile:)

**Comment by pcarranza** [comment]
LFTM :+1: 

Let's wait for @smellsblue if you don't mind

**Comment by smellsblue** [comment]
:+1:

**Pull request merged**
