### PR TITLE
gem: sequel v5.0.0

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR tries to update Sequel to the next major version.

[Changelog](https://github.com/jeremyevans/sequel/blob/master/CHANGELOG)

(I had a weird failure on my local Ruby test suite, seemed unrelated, will test the matrix, too. **Update**: no error there.)

### CODE REVIEW

**Comment by olleolleolle** [comment]
@indirect r?

**Comment by indirect** [comment]
@bundlerbot r+

thanks!

**Comment by olleolleolle** [comment]
It's so fantastic that Sequel maintains 1.9.3 support.

**Comment by olleolleolle** [comment]
@bundlerbot retry

**Pull request merged**
